coveo/search-ui-extensions

src/utils/translation.ts
tests/Utils/translation.spec.ts

This prevent an issue in the interface editor where the registered strings are nuke by an other definition of `toLocaleString` loaded. (Multiple CoveoJsSearch.js loaded)

Use string locales SFINT-2448

---

package-lock.json
package.json

Because Strings.ts is not a module, if its not listed as a side-effects, webpack will snob it.

Add strings of ViewedByCustomer as sideEffects SFINT-2465

---

package.json
src/components/AttachResult/AttachResult.ts
src/components/AttachResult/Events.ts
src/components/AttachResult/Strings.ts
src/components/ResultsFilter/Events.ts
src/components/ResultsFilter/ResultsFilter.ts
src/components/ResultsFilter/Strings.ts
tests/components/AttachResult/AttachResult.spec.ts
tests/components/ResultsFilter/ResultsFilter.spec.ts

Advise if I should add all events/strings in a single file for every component instead ?
Added strings for defaults strings of AttachResult and ResultsFilter
Added events when attaching / detaching result and filtering
SNOW-182

new Events and localization for AttachResult and ResultsFilter components

---

src/components/UserActions/ClickedDocumentList.ts
src/components/UserActions/QueryList.ts
src/components/UserActions/UserActivity.ts
tests/components/UserActions/ClickedDocumentList.spec.ts
tests/components/UserActions/QueryList.spec.ts
tests/components/UserActions/UserActivity.spec.ts

Previously the `DocumentClickedList` component would call the `getActions` method for a `UserProfileModel` with a falsey `userId` value when opening a new chat.
This Pull Request adds a falsey check for `userId`. If falsey, the component is disabled.
Added unit test for the falsey check.
Edit: The scope was expanded to fix the same issue in the `QueryList` component and `UserActivity` component.

Sfint 2496 - Added falsey check for userId in DocumentClickedList Component

---

config/webpack.config.karma.js
package-lock.json
package.json
tests/components/ResultsFilter/ResultsFilter.spec.ts
tests/components/ViewedByCustomer/ViewedByCustomer.spec.ts

karma-webpack does not bubble up errors and warning properly, so the build would pass even if errors occurs at the transpilation stage.
abstiles/webpack-karma-die-hard is a simple webpack plugin that ensure that when such error occurs karma is properly notified of it. I added it to the webpack config used for our tests.
You can see the result (i.e. a failed build) [here](https://travis-ci.org/coveo/search-ui-extensions/builds/589582061).
I also fixed the transpilation issues in the tests: two TS6133 errors (variable declared but not used or read) and a TS6192 (All imports in import declaration are unused). This fix the issues raised in the aforementioned failed build.

fix(SFINT-2577): Add karma-webpack-die-hard

---

README.md

When you clicked the build status badge, you were redirected to the picture of the badge itself
Now, when you click on it, you are redirected to the Travis of the repo.

doc(SFINT-2611): Use Travis stuff, not shields.io

---

src/components/UserActions/UserActions.ts
tests/components/UserActions/UserActions.spec.ts

@jeremierobert-coveo pointed out that we don't need another options for the viewedBy and can use the userId. This does that.

fix(SFINT-2612): Remove duplicate options in UserActions

---

src/components/UserActions/UserActions.ts
tests/components/UserActions/ClickedDocumentList.spec.ts
tests/components/UserActions/UserActions.spec.ts

Custom init options were ignored for the UserActions sub components.

Pass init options for UserActions sub components. SFINT-2759

---

src/components/UserActions/ExpandableList.ts
tests/components/UserActions/ExpandableList.spec.ts

Without the `type=button`  attribute, the default behaviour of the button is to submit the parent form, if there is any. That was a problem in ServiceNow since the whole page is a huge form, clicking on Show More/Less would submit the page and redirect the user. 
SNOW-240

Added type button to the More/Less button in expandable list

---

src/components/UserActions/UserActions.ts
src/components/ViewedByCustomer/ViewedByCustomer.ts
tests/components/UserActions/UserActions.spec.ts
tests/components/ViewedByCustomer/ViewedByCustomer.spec.ts

Jira: https://coveord.atlassian.net/browse/SFINT-2851
If the last cell/row of the result is already quite full, the Viewed By Customer would break in two lines and that didn't render very well.
When 'auto-appending' the ViewedByCustomer in the result, append the ViewedByCustomer in the first cell of the last row of the result frame.
When 'auto-appending' the ViewedByCustomer in the result, find the last row of the result row and create a new 'sibling' row in which there's a cell that include the ViewedByCustomer.
Top, before. Bottom, after.

fix(SFINT-2851): BREAKING Insert ViewedByCustomer in a new row

---

src/components/CopyToClipboard/CopyToClipboard.ts

Changed default UA type on CopyClipboard from "click" to "resultAction" to match the others.

Changed default UA type on CopyClipboard [SFINT-3033]

---

src/components/UserActions/UserActivity.ts

prepend is not supported by antiquated and/or restrictive tech and browser, namely IE11 and LockerService.
insertBefore works pretty much everywhere.
No change in behavior, nor logic, therefore existing tests are actually testing the changes.
If we'd like to test the aforementioned limiters, this IMO should be done in another story.
Source:
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend
https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore in particular example 3.

fix(SFINT-3248): Replace prepend by insertBefore

---

pages/action_button.html
src/Index.ts
src/components/ActionButton/ActionButton.scss
src/components/ActionButton/ActionButton.ts
src/sass/Index.scss
tests/components/ActionButton/ActionButton.spec.ts

This PR adds the _ActionButton_ component. This component is meant to be a reusable button component displaying an icon and/or text with a tooltip.
The button looks like this:
Hovering the button looks like this:

feat(SFINT-3167): Add ActionButton Component

---

pages/toggle_action_button.html
src/Index.ts
src/components/ActionButton/ActionButton.scss
src/components/ActionButton/ActionButton.ts
src/components/ActionButton/ToggleActionButton.scss
src/components/ActionButton/ToggleActionButton.ts
src/sass/Index.scss
tests/components/ActionButton/ActionButton.spec.ts
tests/components/ActionButton/ToggleActionButton.spec.ts

This PR adds the _ToggleActionButton_ component. As its name states, it simply is an _ActionButton_ featuring a toggle state. In addition, to keep things simple, this button supports only having an icon and tooltip. A different icon and tooltip can be displayed when the button is activated.
Using the options, the caller might attach handlers when the button is either clicked, activated, or deactivated.

feat(sfint-3272): Add ToggleActionButton component

---

pages/toggle_action_button.html
src/components/ActionButton/ToggleActionButton.ts
tests/components/ActionButton/ToggleActionButton.spec.ts

Some of the _ToggleActionButton_ options were confusing because their value was kind of the inverse of the option name. For example, the `activatedTooltip` option could have a value like `Deactivate feature xyz`.
These options were renamed like this:
activatedTooltip   --> deactivateTooltip
activatedIcon      --> deactivateIcon
deactivatedTooltip --> activateTooltip
deactivatedIcon    --> activateIcon
This way the option values would read like this:
activateTooltip: 'Activate feature xyz'
deactivateTooltip: 'Deactivate feature xyz'

feat(SFINT-3300): Improve ToggleActionButton option names

---

pages/attached_result.html
src/components/AttachResult/AttachResult.ts
tests/components/AttachResult/AttachResult.spec.ts

Small addition to the AttachResult component to specify the caseId and the field where the articleId can be obtained. For ServiceNow, the articleId is pretty much always the permanentID and the caseID is static on the page. Tested using the local test page.
- Added case and article ids to AttachResult custom events
- Added click event when attaching in AttachResult
SNOW-364

Added case and article ids to AttachResult custom events

---

src/components/UserActions/UserActions.ts
tests/components/UserActions/UserActions.spec.ts

Add a useResponsiveManager option, default to true. Previous behaviour is kept, meaning that if you have hidden, the useResponsiveManager will be inoperant because hidden does super-seed it.
It allows SFINT to use the UserActions without hooking it to the ResponsiveComponentManager, will preserving its other functionality.
Allow other components to be notified of when the UserActions panel is shown or hidden.
It allows SFINT to sync up the state of the ToggleActionButton with the panel when the latter get closed by something else than the button (e.g. query)
- UT
- SAN checked in SFINT

fixeat(SFINT-3295): Improve UserActions interactivity

---

src/components/ActionButton/StatefulActionButton.ts
tests/components/ActionButton/StatefulActionButton.spec.ts
tests/components/ActionButton/ToggleActionButton.spec.ts

Ensure the inner state is updated first, so `activated` is true the first time after the first `setActivated(true)` and therefore the second is no-opped.
This is 'suffisant' as a fix, however, as the Panel also has a state, it's supposed to do the same checks and to update its inner states ASAP in the execution, or at the very least before doing any 'outside' communications.
This will be done in a future PR.
SAN Check in SFINT
UT for new code
UT for this peculiar scenarii.
Both UT suites have been tested with and without the changeset, they do fail properly when the fix is not there ✔️

Fix/SFINT-3352: Ensure internal state is updated first.

---

tests/components/ActionButton/ToggleActionButton.spec.ts
tests/utils.ts

Flaky UT issue from #86, see https://travis-ci.org/github/coveo/search-ui-extensions/builds/712557300.
I was not able to 'pin-point' with certitude what caused the flakiness, due to the issue being, well flaky (and thus I'm not 💯 confident it'll be fixed but I think it will)
Two fixes:
- Do not modify `activateSpy` and `deactivateSpy` they're used as default options for the component instantiation, which can cause test leakage.
- Ensure all events listener have completed their job before checking the spies. This also prevents test leakage (you could have the eventListener of the test n-1 executed during the execution of the test n) and also that we're actually testing what we want. (We do not want to 'miss' a double call because the second call occurs after the expectation.

test(SFINT-3352): Safer tests

---

package-lock.json
package.json
tests/components/UserActions/ClickedDocumentList.spec.ts
tests/components/UserActions/ExpandableList.spec.ts
tests/components/UserActions/QueryList.spec.ts
tests/components/UserActions/ResponsiveUserActions.spec.ts
tests/components/UserActions/UserActions.spec.ts
tests/components/UserActions/UserActivity.spec.ts
tests/components/ViewedByCustomer/ViewedByCustomer.spec.ts
tests/models/UserProfilingModel.spec.ts
tests/utils.ts

While investigating SFINT-3353, I discovered several issues in the UT
The actual 'fix' for SFINT-3353 will be done in a second term to have a clear split between refacto' and fix.
https://jasmine.github.io/api/3.6/global.html#expect
TL;DR: Use matchers after expect. Always.
```ts
it('sometest'()=>{
expect(false);
expect(true);
}
```
This will pass. expect is not Assert. This will not pass:
```ts
it('sometest'()=>{
expect(false).toBeTrue();
expect(true).toBeTrue();
}
```
Various, various issues. My goal was to, whenever possible to 'flatten' and synchronize the tests, and avoid delay as much as possible (except when used to 'flush' the promise stack see `waitForPromiseCompletions`).
Doing an `await(delay(()=>{})` ensure that all Promises are resolved before continuing. (assuming there's no …

test(SFINT-3353): Test cleaning

---

src/components/UserActions/ClickedDocumentList.ts
src/components/UserActions/QueryList.ts
src/components/UserActions/UserActions.scss
tests/components/UserActions/ClickedDocumentList.spec.ts
tests/components/UserActions/QueryList.spec.ts

Feat/sfint 4378 added a tooltip to show origin1 on clickedDocList and queriesList

---

src/components/UserActions/Strings.ts
src/components/UserActions/UserActions.scss
src/components/UserActions/UserActions.ts
tests/components/UserActions/UserActions.spec.ts

New way of explaining why there are no user actions visible.
Where the user actions are not enabled (404 response) :
When we get an error or no user actions:

feat(SFINT-4388) no results text when no user actions

---

config/tsconfig.json
src/components/UserActions/Strings.ts
src/components/UserActions/UserActivity.ts
tests/components/UserActions/UserActivity.spec.ts

#nofilter
#withfilter 
#withallactionsfiltered
Don't think the third case is actually possible but I thought I still needed to include it.

feat(sfint-4354) custom events filtering
