coveo/search-ui-extensions

- .prettierrc
- config/tsconfig.json
- config/webpack.config.js
- config/webpack.config.karma.js
- package.json
- pages/index.html
As you can see now it build to lib coveo-searcch-ui-extension one in the bin/js/es6 folder and the other in th bin/js/commonjs folder.
> Dual Build

- .prettierrc.json
- package.json
Remove prettier inline config
Replace Unix-only command by rimraf for sweet OS-agnostic development
> Clean-up package.json

- .travis.yml
- scripts/before.deploy.js
I added a script to change the version in the package.json before deployment.
> BUG The beta npm package build does not work

- config/tsconfig.json
- config/webpack.config.js
- package.json
- pages/index.html
- scripts/dev.server.js
use the package.json module field
> Fully support es6

- pages/index.html
There's a nested coveo-main-section in the current template leading to not really usable dev page. This fix that,
> Remove nested coveo-main-section.

- package-lock.json
- src/components/UserActions/UserActions.ts
- tests/components/UserActions/UserActions.spec.ts
See SFINT-2453
Fix an issue where an empty string can be use as a userId
> Disable User Actions when userId is falsy SFINT-2453

- src/components/UserActions/ClickedDocumentList.ts
- src/components/UserActions/QueryList.ts
- src/components/UserActions/UserActions.scss
- tests/components/UserActions/ClickedDocumentList.spec.ts
- tests/components/UserActions/QueryList.spec.ts
Added "duplicate" icon to items in the recently clicked documents list
Added "search" icon to the items in the recent queries list
Wrote tests making sure the icon appeared in the HTML of every displayed list item
> Add icons to User Actions Summary SFINT-2374

- config/karma.config.js
- package-lock.json
- package.json
Simple change in the config, only ensure that the version of chrome being used is the one of puppeteer not the one of the system.
This allow in particular to run tests on WSL.
> fix(SFINT-2563) Add CHROME_BIN export in karma config

- src/components/ViewedByCustomer/ViewedByCustomer.ts
- tests/components/ViewedByCustomer/ViewedByCustomer.spec.ts
Changed the error to a warn to avoid the crash of the page and just to be a bit less brutal.
> fix(SFINT-2686): Change error to warn

- README.md
- package-lock.json
- package.json
- pages/index.html
- src/components/UserActions/UserActions.ts
- tests/components/UserActions/UserActions.spec.ts
This really looks odd. That's why we removed it.
> [SFINT-2847] Viewed by customer is no longer automagicly injected in a table layout

- src/Index.ts
- src/components/ResultAction/ResultAction.ts
- tests/components/ResultAction/ResultAction.spec.ts
Add generic result action component to search-ui-extension repo
> feat(SFINT-2977): Add generic result action component

- package.json
> fix(SFINT-3009): Forgot to flag side effect

- src/components/CopyToClipboard/CopyToClipboard.ts
- tests/components/CopyPaste/CopyPaste.spec.ts
* Added UTs.
* Added an option to set the tooltip success label.
* Ensure the success label is shown on success.
(This PR is therefore called shame)
> SFINT-3009 Fix an issue where the text is not changed when clicked

- src/components/CopyToClipboard/CopyToClipboard.ts
- tests/components/CopyPaste/CopyPaste.spec.ts
See here the new behavior https://share.vidyard.com/watch/27BHA6A8FiegmLnT8mcR1v?
> fix(SFINT-3034): Make the tooltip flashing more reliable

- config/tsconfig.json
- config/webpack.config.js
- scripts/svg.js
- src/utils/icons.ts
> Fix/SFINT-3128 es6 is now 100% es6

- package-lock.json
- src/components/UserActions/UserActions.scss
- src/components/UserActions/UserActivity.ts
- src/utils/time.ts
- tests/Utils/time.spec.ts
- tests/components/UserActions/UserActivity.spec.ts
- Added formatDateAndTime utility function to return full formatted date and time
- Added this new date time format to the user activity timestamp.
- Moved the timestamp beside the activity title
- Added and modified UT accordingly
> [feat/SFINT-3189] Added date to user activity timestamp

- README.md
This PR adds a disclaimer regarding the backward compatibility for this repository.
* Indicates the project is in its pre-release phase.
* Indicates JavaScript compatibility is not guaranteed.
* Indicates TypeScript definitions are for internal use.
> chore(SFINT-3304): Add backward compatibility disclaimer

- README.md
Self-explanatory.
Come from #80
> Update node requirement to node 10

- src/components/UserActions/UserActions.ts
- tests/components/UserActions/UserActions.spec.ts
Similar to #86 but for the UserAction.
That removes another potential StackOverflow error :)
> feat(SFINT-3353): Ensure UserAction Panel state is updated first

- src/components/UserActions/ClickedDocumentList.ts
- tests/components/UserActions/ClickedDocumentList.spec.ts
open in a new tab option was ignore as a result of the previous PR
> Fix/sfint-3372 Support open in a new tab

- adr/components/UserActions/UserActions/ShowViewedByCustomer.md
fix: Change all references of bitbucket to github for all remaining files
**Please repo owner review carefully. This PR has been generated by a script and it has not been tested.**
JIRA CA-97
> Change all references of bitbucket to github

- .deployment.config
Testing if veracode would work for ts files!
WORK-1437
> Added Veracode certifier

- src/components/UserActions/UserActions.scss
- src/components/UserActions/UserActions.ts
- src/sass/Index.scss
- src/sass/ResultActionMenu.scss
- src/sass/SLDSSpinner.scss
- tests/components/UserActions/UserActions.spec.ts
fix deprecated sass lines
added loading spinner during user actions load
https://user-images.githubusercontent.com/2488155/151622401-0ddaaef2-7d2f-43d5-acd2-403c89b99d14.mp4
> feat(SFINT-4203) Add loading spinner during user actions call

- package-lock.json
- package.json
chore/update search-ui to 2.10089.4
> chore/update search-ui to 2.10089.4

- ,github/workflows/publish.yml
- package.json
Please feel free to point me to improvements to the GHA!
> feat(github action): publish to npm via GHA

- package-lock.json
- package.json
Bump version for release v0.1.1
> Bump version for release v0.1.1

- .deployment.config
> Replace veracode for snyk code

- Jenkinsfile
- config/webpack.config.karma.js
- package-lock.json
- package.json
dependency conflict failed the build
SVCINT-1979
> peer dependencies failed

- .deployment.config
- Jenkinsfile
Same thing, changed QA for STG since QA is deprecated!
SVCINT-1984
> Changed QA for STG in deployment pipeline

- package-lock.json
update dependencies with `npm audit fix`
> chore/update dependencies with `npm audit fix`

- package-lock.json
- package.json
remove string-replace-webpack-plugin it was unused and it was blocking a PR from dependabot to update dependencies to fix a critical vuln
> chore: remove string-replace-webpack-plugin it was unused

- .deployment.config
Not in use anymore.
I'll let you decide whether you keep Snyk here since this is an open-source project.
> Drop legacy config
